server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customerdb?createDatabaseIfNotExist=true
    username: root  
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Tự động cập nhật database
    show-sql: true       # Hiển thị SQL trên console
    database: mysql
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect 

eureka:
  instance:
    hostname: localhost # Đặt lại thành localhost
    prefer-ip-address: true # Dùng IP thay vì hostname
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/


